name: Update Basketball Data and Model

on:
  schedule:
    - cron: '0 10 * * *'

  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("dplyr", "readr", "tibble", "tidyr"))'

      - name: Run update script
        run: Rscript main.R

      - name: Commit and push if changes exist
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git pull
          git add -A
          timestamp=$(date -u)
          git commit -m "Last updated: ${timestamp}" || exit 0
          git push origin main || echo "No changes to commit"
